[package]
edition = "2018"
name = "zash"
version = "0.1.0"

[dependencies]
dirs = "4.0.0"
rustyline = "9.0.0"
rustyline-derive = "0.5.0"
signal-hook = "0.3.10"
structopt = "0.3.25"
whoami = "1.1.5"
colored = "2.0.0"